// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1QaL80o4v38aQoDdOp49YwivE-AKhpU',
    appId: '1:941563514043:web:987b71165cbb6b81bbad9e',
    messagingSenderId: '941563514043',
    projectId: 'hci-project-e29b9',
    authDomain: 'hci-project-e29b9.firebaseapp.com',
    storageBucket: 'hci-project-e29b9.firebasestorage.app',
    measurementId: 'G-8GK5RMY17Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACZTk2gDmRlFgpeHLc_miIaAjPHy_9_FE',
    appId: '1:941563514043:android:275a4a48580818d0bbad9e',
    messagingSenderId: '941563514043',
    projectId: 'hci-project-e29b9',
    storageBucket: 'hci-project-e29b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJiuDkrE7eEvN9lfGaJgZlwY6sURMF8jg',
    appId: '1:941563514043:ios:aa6552dd3001d556bbad9e',
    messagingSenderId: '941563514043',
    projectId: 'hci-project-e29b9',
    storageBucket: 'hci-project-e29b9.firebasestorage.app',
    iosClientId: '941563514043-2f68p4kdemhdomqv2stpk0ku0hl6bits.apps.googleusercontent.com',
    iosBundleId: 'com.example.hciProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJiuDkrE7eEvN9lfGaJgZlwY6sURMF8jg',
    appId: '1:941563514043:ios:aa6552dd3001d556bbad9e',
    messagingSenderId: '941563514043',
    projectId: 'hci-project-e29b9',
    storageBucket: 'hci-project-e29b9.firebasestorage.app',
    iosClientId: '941563514043-2f68p4kdemhdomqv2stpk0ku0hl6bits.apps.googleusercontent.com',
    iosBundleId: 'com.example.hciProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt1QaL80o4v38aQoDdOp49YwivE-AKhpU',
    appId: '1:941563514043:web:546690ca0ac3d7e3bbad9e',
    messagingSenderId: '941563514043',
    projectId: 'hci-project-e29b9',
    authDomain: 'hci-project-e29b9.firebaseapp.com',
    storageBucket: 'hci-project-e29b9.firebasestorage.app',
    measurementId: 'G-J9VJHCJSTG',
  );
}
